name: ActionNotifier

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@master
      - name: whatsapp-notify
        id: whatsapp-notify
        env:
          account_sid: ${{ secrets.twilio_account_sid }}
          auth_token: ${{ secrets.twilio_auth_token }}
          to_whatsapp_no: ${{ secrets.twilio_to_whatsapp_no }}

        uses: atifazeez77/whatsapp-push-notify-action@master

      - name: Run
        run: |
          echo 'Start!'
